### ISSUE TITLE
Does not shrink

### ISSUE THREAD

**Issue by gajus** [digidem/react-dimensions#10]
``` js
<div className='viewport'>
    <div className='foo'>
        <div className='bar'>
            <Component />
        </div>
    </div>
</div>
```

``` css
.viewport {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    display: flex;
    flex-direction: column;
}

.foo {
    display: flex;
    flex-direction: row;
    flex-grow: 1;
}

.bar {
    display: flex;
    flex-direction: column;
    flex-grow: 1;
}
```

With this setup, `react-dimensions` will make component grow, but will not make it shrink. This is because `<Component />` gets fixed width that `.bar` container will respect (`.foo` contents will overflow).

The only way I found I can fix this is by adding `max-width: -webkit-fill-available` to the `.bar` style.
